# Site settings
title: Nimo Ni - My unconscious mind, a huge garbage
description: 'Nimo Ni - My unconscious mind, a huge garbage'
url: 'http://wodeni.github.io/nimo-site'
baseurl: '/nimo-site/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Nimo Wode Ni'
  email: wn2155@columbia.edu
  # twitter_username: joshgerdes
  # facebook_username: joshgerdes
  github_username:  wodeni
  linkedin_username:  wode-ni

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
