# Site settings
title: Wode "Nimo" Ni
description: 'In the ocean of code, I swim.'
url: 'http://wodeni.github.io'
baseurl: '/'
# url: 'http://www.columbia.edu'
# baseurl: '/~wn2155/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Wode "Nimo" Ni'
  email: wn2155@columbia.edu
  # twitter_username: joshgerdes
  # facebook_username: joshgerdes
  github_username:  wodeni
  linkedin_username:  wode-ni

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
